name: Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write


jobs:
  bors:
    name: Bors
    runs-on: ubuntu-latest
    steps:
      - run: true
